### ISSUE TITLE
Add read more / read less support to review text

### ISSUE THREAD

**Issue by Smuzzy-waiii** [acmpesuecc/menumemory#2]
Currently if the review text is too  long, it just renders it as such taking up a lot of space, which is unideal. For eg:
<img width="427" alt="image" src="https://github.com/user-attachments/assets/4197dfa5-75fc-495c-8705-f8d8f3430d4d">

Let the text have a max length after which it is truncated as "lorem ipsum gamma beta... [see more]()" which expands to show the whole text on see more and show a "see less" when the text is expanded fully. You should be able to find libraries on pub.dev which provide this exact functionality

Example of how it would look like (refer the [figma design](https://www.figma.com/design/soNxFzBVn5t5vZrbkTjCnu/Restaurant-Visit-Tracker?node-id=0-1&t=nMHPID03iy7o1oJM-1) for more):
<img width="515" alt="image" src="https://github.com/user-attachments/assets/8d8e652e-7674-4621-b669-c2a87567b024">

**Comment by master-wayne7** [comment]
Hello @Smuzzy-waiii I can work on it can you assign it to me?

**Comment by Smuzzy-waiii** [comment]
!assign @master-wayne7 60

**Comment by master-wayne7** [comment]
@Smuzzy-waiii I have fixed the issue in the PR #7

**Comment by Smuzzy-waiii** [comment]
!deassign

**Comment by Smuzzy-waiii** [comment]
This issue was solved by #7

**Comment by master-wayne7** [comment]
@Smuzzy-waiii just had a question I am new to open source so can you please let me know what are these bounty points and what can I do with them?
