### ISSUE TITLE
Setup Firestore Security Rules

### ISSUE THREAD

**Issue by Smuzzy-waiii** [acmpesuecc/menumemory#5]
Currently everyone has all access to the whole firestore database. This permission rule is way too wide, violates the principle of least priviledge and is a security risk. Your task is to write firestore security rules to enforce the following policies:

- Everyone has read access to restaurants. no signedin user has write, delete access to restaurants (can only be edited from cloud functions and the FB admin sdk)
- In the /users collection, signed in users have access to read,write,delete only inside their user document ie user123 has all access to /users/user123 and /users/user123/* 
- Signed in users cannot read,write or delete other users in the users collection

**Comment by Smuzzy-waiii** [comment]
!assign @Srijan1904

**Comment by Am3li1** [comment]
can i get assigned to this

**Comment by Smuzzy-waiii** [comment]
!assign @Am3li1

**Comment by Srijan1904** [comment]
!withdraw

**Comment by Smuzzy-waiii** [comment]
!assign @Am3li1

**Comment by Smuzzy-waiii** [comment]
!assign @Am3li1

**Comment by Smuzzy-waiii** [comment]
@Am3li1 The bot will deassign you in 45mins. If you need more time, show your progress and I can extend the time. Please text/call me at 8618950413 for firebase access

**Comment by Smuzzy-waiii** [comment]
@Am3li1 I am extending for another 45 mins

**Comment by Smuzzy-waiii** [comment]
!deassign

**Comment by Smuzzy-waiii** [comment]
!assign @Am3li1 45

**Comment by Smuzzy-waiii** [comment]
!deassign

**Comment by Smuzzy-waiii** [comment]
Resolved by #8
